#!/usr/bin/perl

# -------------------------------------------------
#
# Small utility program to be able to push
# commits to multiple remote origins fast with git.
#
# ~331uw13
# -------------------------------------------------



use strict;
use warnings;
use feature qw(switch);

use Config::Tiny;

our $version = "0.01";
our $home = $ENV{"HOME"};
#our $cfgdir = "$home/.gitrepo-update";
#our $basecfg = "$cfgdir/basecfg.ini";

our $git_ignore = ".gitignore";
our $cwdcfg_filename = ".gitrepo-update.ini";

our $prefix_prog_name = "gitrepo-update";
our $prefix      = "\033[1;36m$prefix_prog_name\033[90m:\033[0m ";
our $prefix_err  = "\033[1;31m$prefix_prog_name\033[90m:\033[0m ";
our $prefix_warn = "\033[1;33m$prefix_prog_name\033[90m:\033[0m ";
our $prefix_indent = ' ' x (length($prefix_prog_name)+2);

sub print_help {
    print(
        "\n".
        "  -n              ; Create new config.\n".
        "  -l              ; List all remote origins in current config.\n".
        "  -a [url]        ; Add new remote origin to current config.\n".
        "\n".
        "  -p [message]    ; Create commit and push to all remote origins in current config.\n".
        "\n".
        "\033[90mversion $version\033[0m\n"
    );
    exit();
}

sub get_config_remote_origins {
    my $cfg = Config::Tiny->read($cwdcfg_filename); 
    my $arr = $cfg->{config}->{remote_origins};
    return @$arr;
}


sub create_file {
    open(FH, '>', $_[0]) or die $!;
    print FH $_[1];
    close(FH);
}
sub append_file {
    open(FH, '>>', $_[0]) or die $!;
    print FH $_[1];
    close(FH);
}

sub create_config {
    if(-e $cwdcfg_filename) {
        print("$prefix_err Current working directory already has configuration file. Not overwriting.\n");
        return;
    }
 
    create_file($cwdcfg_filename, 
    "[config]\n".
    "remote_origins[]=\n");

    print("$prefix Created '$cwdcfg_filename'\n");
        
    print("$prefix Add '$cwdcfg_filename' to '$git_ignore'? (y/n): ");
    my $input = <STDIN>;

    if(length($input) == 0) {
        return;
    }


    if(!(uc(substr($input, 0, 1)) eq "Y")) {
        print("Not editing .gitignore\n");
        return;
    }

    if(!-e $git_ignore) {
        create_file($git_ignore,
        "$cwdcfg_filename\n");
    }
    else {
        # Check first it doesnt exist already.
        open(FH, '<', $git_ignore) or die $!;

        while(my $line = <FH>) {
            if($line eq "$cwdcfg_filename\n") {
                return;
            }
        }

        append_file($git_ignore, "$cwdcfg_filename\n");
        close(FH);
    }
}

sub cwdcfg_exists {
    if(!-e $cwdcfg_filename) {
        print("$prefix_err There is no configuration in current working directory.\n");
        return 0;
    }
    return 1;
}

sub add_remote_origin {
    if(!cwdcfg_exists()) {
        print("$prefix_err Cant add new remote origin due to previous error.\n");
        return;
    }
    my @remote_origins = get_config_remote_origins();
    my $num_origins = scalar(@remote_origins);
    my $cfg = Config::Tiny->read($cwdcfg_filename);

    $cfg->{config}->{remote_origins}->[$num_origins] = $_[0];
    $cfg->write($cwdcfg_filename);
}

sub print_line {
    print("\033[2;90m-----\033[0m\n");
}
            
sub push_commit {
    my $message = $_[0];
    my $branch = $_[1];

    if(length($message) == 0) {
        return;
    }
    if(length($branch) == 0) {
        return;
    }

    system("git add .");
    system("git commit -m \"$message\"");
    system("git show --summary");

    print("$prefix Commit is going to be pushed into following remote origins:\n");
    my @remote_origins = get_config_remote_origins();
    foreach my $origin (@remote_origins) {
        if(length($origin) > 0) {
            print("$prefix_indent - $origin\n");
        }
    }

    print_line();
    print("\nReady to push commit? (y/n): ");
    my $input = <STDIN>;
    
    if(!(uc(substr($input, 0, 1)) eq "Y")) {
        print("$prefix_err Commit not pushed.\n");
        return;
    }

    foreach my $origin (@remote_origins) {
        if(length($origin) > 0) {
            system("git remote set-url origin $origin");
            system("git push -u origin $branch");
        }
    }
}

sub process_flag {
    my $flag = $_[0];
    my $index = $_[1];

    given($flag) {
   
        when("-n") {
            create_config();
            return 0;
        }
        when("-a") {
            if(!defined($ARGV[$index+1])) {
                print_help();
            }
            add_remote_origin($ARGV[$index+1]);
            return 2;
        }
        when("-l") {
            if(!cwdcfg_exists()) {
                print("$prefix_err Cant list remote origins due to previous error.\n");
            }
            print("$prefix Current working directory config remote origins:\n");
            my @remote_origins = get_config_remote_origins();
            foreach my $origin (@remote_origins) {
                if(length($origin) > 0) {
                    print("$prefix_indent - $origin\n");
                }
            }
            return 0;
        }
        when("-p") {
            if(!defined($ARGV[$index+1])) {
                print("$prefix_err Commit message and branch name is needed.");
                print_help();
                return 0;
            }
            if(!defined($ARGV[$index+2])) {
                print("$prefix_err Branch name is needed.");
                print_help();
                return 1;
            }

            push_commit($ARGV[$index+1], $ARGV[$index+2]);

            return 2;
        }

    }

    return 0;
}

sub main {

    if(scalar(@ARGV) <= 0) {
        print("$prefix_err No action selected.\n");
        print_help();
    }

    my $num_args = scalar(@ARGV);
    
    for(my $i = 0; $i < $num_args; ) {
        my $i_skip = process_flag($ARGV[$i], $i);

        $i += 1 + $i_skip;
    }
}


main();
